// pkg/proto/filesystem.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/filesystem.proto

package fs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Read request
type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`  // Volume identifier
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`                       // Inode identifier
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`                     // Read offset
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`                         // Number of bytes to read
	HandleId      uint64                 `protobuf:"varint,5,opt,name=handle_id,json=handleId,proto3" json:"handle_id,omitempty"` // File handle from Open
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_proto_filesystem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{0}
}

func (x *ReadRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *ReadRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *ReadRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ReadRequest) GetHandleId() uint64 {
	if x != nil {
		return x.HandleId
	}
	return 0
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // File data
	Eof           bool                   `protobuf:"varint,2,opt,name=eof,proto3" json:"eof,omitempty"`  // End of file marker
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_proto_filesystem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{1}
}

func (x *ReadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadResponse) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

// Write request
type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`  // Volume identifier
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`                       // Inode identifier
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`                     // Write offset
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                          // Data to write
	HandleId      uint64                 `protobuf:"varint,5,opt,name=handle_id,json=handleId,proto3" json:"handle_id,omitempty"` // File handle from Open
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_proto_filesystem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{2}
}

func (x *WriteRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *WriteRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *WriteRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WriteRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WriteRequest) GetHandleId() uint64 {
	if x != nil {
		return x.HandleId
	}
	return 0
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  int64                  `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"` // Number of bytes written
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_proto_filesystem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{3}
}

func (x *WriteResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

// Open file
type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"` // Volume identifier
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`                      // Inode to open
	Flags         uint32                 `protobuf:"varint,3,opt,name=flags,proto3" json:"flags,omitempty"`                      // Open flags
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_proto_filesystem_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{4}
}

func (x *OpenRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *OpenRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *OpenRequest) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type OpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandleId      uint64                 `protobuf:"varint,1,opt,name=handle_id,json=handleId,proto3" json:"handle_id,omitempty"` // File handle for operations
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_proto_filesystem_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{5}
}

func (x *OpenResponse) GetHandleId() uint64 {
	if x != nil {
		return x.HandleId
	}
	return 0
}

// Release (close) file
type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`  // Volume identifier
	HandleId      uint64                 `protobuf:"varint,2,opt,name=handle_id,json=handleId,proto3" json:"handle_id,omitempty"` // File handle to release
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_proto_filesystem_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{6}
}

func (x *ReleaseRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *ReleaseRequest) GetHandleId() uint64 {
	if x != nil {
		return x.HandleId
	}
	return 0
}

// Create file
type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"` // Volume identifier
	Parent        uint64                 `protobuf:"varint,2,opt,name=parent,proto3" json:"parent,omitempty"`                    // Parent directory inode
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                         // File name
	Mode          uint32                 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`                        // File mode (permissions)
	Flags         uint32                 `protobuf:"varint,5,opt,name=flags,proto3" json:"flags,omitempty"`                      // Open flags
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_proto_filesystem_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{7}
}

func (x *CreateRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *CreateRequest) GetParent() uint64 {
	if x != nil {
		return x.Parent
	}
	return 0
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *CreateRequest) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

// Create directory
type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"` // Volume identifier
	Parent        uint64                 `protobuf:"varint,2,opt,name=parent,proto3" json:"parent,omitempty"`                    // Parent directory inode
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                         // Directory name
	Mode          uint32                 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`                        // Directory mode
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_proto_filesystem_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{8}
}

func (x *MkdirRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *MkdirRequest) GetParent() uint64 {
	if x != nil {
		return x.Parent
	}
	return 0
}

func (x *MkdirRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MkdirRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// Node response (for Create, Mkdir, Lookup)
type NodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inode         uint64                 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`                       // Created/existing inode
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`             // Generation number
	Attr          *GetAttrResponse       `protobuf:"bytes,3,opt,name=attr,proto3" json:"attr,omitempty"`                          // Node attributes
	HandleId      uint64                 `protobuf:"varint,4,opt,name=handle_id,json=handleId,proto3" json:"handle_id,omitempty"` // File handle for operations
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeResponse) Reset() {
	*x = NodeResponse{}
	mi := &file_proto_filesystem_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResponse) ProtoMessage() {}

func (x *NodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeResponse.ProtoReflect.Descriptor instead.
func (*NodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{9}
}

func (x *NodeResponse) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *NodeResponse) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *NodeResponse) GetAttr() *GetAttrResponse {
	if x != nil {
		return x.Attr
	}
	return nil
}

func (x *NodeResponse) GetHandleId() uint64 {
	if x != nil {
		return x.HandleId
	}
	return 0
}

// Get file/directory attributes
type GetAttrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"` // Volume identifier
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`                      // Inode to query
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttrRequest) Reset() {
	*x = GetAttrRequest{}
	mi := &file_proto_filesystem_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttrRequest) ProtoMessage() {}

func (x *GetAttrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttrRequest.ProtoReflect.Descriptor instead.
func (*GetAttrRequest) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{10}
}

func (x *GetAttrRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *GetAttrRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

type GetAttrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ino           uint64                 `protobuf:"varint,1,opt,name=ino,proto3" json:"ino,omitempty"`                               // Inode number
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`                             // File type and mode
	Nlink         uint32                 `protobuf:"varint,3,opt,name=nlink,proto3" json:"nlink,omitempty"`                           // Number of hard links
	Uid           uint32                 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`                               // Owner user ID
	Gid           uint32                 `protobuf:"varint,5,opt,name=gid,proto3" json:"gid,omitempty"`                               // Owner group ID
	Rdev          uint64                 `protobuf:"varint,6,opt,name=rdev,proto3" json:"rdev,omitempty"`                             // Device ID (if special file)
	Size          uint64                 `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`                             // Size in bytes
	Blocks        uint64                 `protobuf:"varint,8,opt,name=blocks,proto3" json:"blocks,omitempty"`                         // Number of 512-byte blocks
	AtimeSec      int64                  `protobuf:"varint,9,opt,name=atime_sec,json=atimeSec,proto3" json:"atime_sec,omitempty"`     // Last access time (seconds)
	AtimeNsec     int64                  `protobuf:"varint,10,opt,name=atime_nsec,json=atimeNsec,proto3" json:"atime_nsec,omitempty"` // Last access time (nanoseconds)
	MtimeSec      int64                  `protobuf:"varint,11,opt,name=mtime_sec,json=mtimeSec,proto3" json:"mtime_sec,omitempty"`    // Last modification time (seconds)
	MtimeNsec     int64                  `protobuf:"varint,12,opt,name=mtime_nsec,json=mtimeNsec,proto3" json:"mtime_nsec,omitempty"` // Last modification time (nanoseconds)
	CtimeSec      int64                  `protobuf:"varint,13,opt,name=ctime_sec,json=ctimeSec,proto3" json:"ctime_sec,omitempty"`    // Last status change time (seconds)
	CtimeNsec     int64                  `protobuf:"varint,14,opt,name=ctime_nsec,json=ctimeNsec,proto3" json:"ctime_nsec,omitempty"` // Last status change time (nanoseconds)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttrResponse) Reset() {
	*x = GetAttrResponse{}
	mi := &file_proto_filesystem_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttrResponse) ProtoMessage() {}

func (x *GetAttrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttrResponse.ProtoReflect.Descriptor instead.
func (*GetAttrResponse) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{11}
}

func (x *GetAttrResponse) GetIno() uint64 {
	if x != nil {
		return x.Ino
	}
	return 0
}

func (x *GetAttrResponse) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *GetAttrResponse) GetNlink() uint32 {
	if x != nil {
		return x.Nlink
	}
	return 0
}

func (x *GetAttrResponse) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetAttrResponse) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *GetAttrResponse) GetRdev() uint64 {
	if x != nil {
		return x.Rdev
	}
	return 0
}

func (x *GetAttrResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetAttrResponse) GetBlocks() uint64 {
	if x != nil {
		return x.Blocks
	}
	return 0
}

func (x *GetAttrResponse) GetAtimeSec() int64 {
	if x != nil {
		return x.AtimeSec
	}
	return 0
}

func (x *GetAttrResponse) GetAtimeNsec() int64 {
	if x != nil {
		return x.AtimeNsec
	}
	return 0
}

func (x *GetAttrResponse) GetMtimeSec() int64 {
	if x != nil {
		return x.MtimeSec
	}
	return 0
}

func (x *GetAttrResponse) GetMtimeNsec() int64 {
	if x != nil {
		return x.MtimeNsec
	}
	return 0
}

func (x *GetAttrResponse) GetCtimeSec() int64 {
	if x != nil {
		return x.CtimeSec
	}
	return 0
}

func (x *GetAttrResponse) GetCtimeNsec() int64 {
	if x != nil {
		return x.CtimeNsec
	}
	return 0
}

// Set attributes
type SetAttrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"` // Volume identifier
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`                      // Inode to modify
	Valid         uint32                 `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`                      // Mask of fields to set
	Attr          *GetAttrResponse       `protobuf:"bytes,4,opt,name=attr,proto3" json:"attr,omitempty"`                         // Attributes to set
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAttrRequest) Reset() {
	*x = SetAttrRequest{}
	mi := &file_proto_filesystem_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAttrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAttrRequest) ProtoMessage() {}

func (x *SetAttrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAttrRequest.ProtoReflect.Descriptor instead.
func (*SetAttrRequest) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{12}
}

func (x *SetAttrRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *SetAttrRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *SetAttrRequest) GetValid() uint32 {
	if x != nil {
		return x.Valid
	}
	return 0
}

func (x *SetAttrRequest) GetAttr() *GetAttrResponse {
	if x != nil {
		return x.Attr
	}
	return nil
}

type SetAttrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attr          *GetAttrResponse       `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"` // Updated attributes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAttrResponse) Reset() {
	*x = SetAttrResponse{}
	mi := &file_proto_filesystem_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAttrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAttrResponse) ProtoMessage() {}

func (x *SetAttrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAttrResponse.ProtoReflect.Descriptor instead.
func (*SetAttrResponse) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{13}
}

func (x *SetAttrResponse) GetAttr() *GetAttrResponse {
	if x != nil {
		return x.Attr
	}
	return nil
}

// Lookup entry in directory
type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"` // Volume identifier
	Parent        uint64                 `protobuf:"varint,2,opt,name=parent,proto3" json:"parent,omitempty"`                    // Parent directory inode
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                         // Entry name to lookup
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_proto_filesystem_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{14}
}

func (x *LookupRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *LookupRequest) GetParent() uint64 {
	if x != nil {
		return x.Parent
	}
	return 0
}

func (x *LookupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Read directory
type ReadDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`  // Volume identifier
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`                       // Directory inode
	HandleId      uint64                 `protobuf:"varint,3,opt,name=handle_id,json=handleId,proto3" json:"handle_id,omitempty"` // Directory handle
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`                     // Read offset
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDirRequest) Reset() {
	*x = ReadDirRequest{}
	mi := &file_proto_filesystem_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirRequest) ProtoMessage() {}

func (x *ReadDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirRequest.ProtoReflect.Descriptor instead.
func (*ReadDirRequest) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{15}
}

func (x *ReadDirRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *ReadDirRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *ReadDirRequest) GetHandleId() uint64 {
	if x != nil {
		return x.HandleId
	}
	return 0
}

func (x *ReadDirRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ReadDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DirEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"` // Directory entries
	Eof           bool                   `protobuf:"varint,2,opt,name=eof,proto3" json:"eof,omitempty"`        // End of directory marker
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDirResponse) Reset() {
	*x = ReadDirResponse{}
	mi := &file_proto_filesystem_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirResponse) ProtoMessage() {}

func (x *ReadDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirResponse.ProtoReflect.Descriptor instead.
func (*ReadDirResponse) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{16}
}

func (x *ReadDirResponse) GetEntries() []*DirEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ReadDirResponse) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type DirEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inode         uint64                 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`   // Entry inode
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // Entry offset
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`      // Entry name
	Type          uint32                 `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`     // Entry type
	Attr          *GetAttrResponse       `protobuf:"bytes,5,opt,name=attr,proto3" json:"attr,omitempty"`      // Entry attributes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirEntry) Reset() {
	*x = DirEntry{}
	mi := &file_proto_filesystem_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirEntry) ProtoMessage() {}

func (x *DirEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirEntry.ProtoReflect.Descriptor instead.
func (*DirEntry) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{17}
}

func (x *DirEntry) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *DirEntry) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DirEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirEntry) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *DirEntry) GetAttr() *GetAttrResponse {
	if x != nil {
		return x.Attr
	}
	return nil
}

// Unlink (delete) file
type UnlinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"` // Volume identifier
	Parent        uint64                 `protobuf:"varint,2,opt,name=parent,proto3" json:"parent,omitempty"`                    // Parent directory inode
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                         // File name to delete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkRequest) Reset() {
	*x = UnlinkRequest{}
	mi := &file_proto_filesystem_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkRequest) ProtoMessage() {}

func (x *UnlinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkRequest.ProtoReflect.Descriptor instead.
func (*UnlinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{18}
}

func (x *UnlinkRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *UnlinkRequest) GetParent() uint64 {
	if x != nil {
		return x.Parent
	}
	return 0
}

func (x *UnlinkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Rename entry
type RenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`     // Volume identifier
	OldParent     uint64                 `protobuf:"varint,2,opt,name=old_parent,json=oldParent,proto3" json:"old_parent,omitempty"` // Old parent directory inode
	OldName       string                 `protobuf:"bytes,3,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`        // Old name
	NewParent     uint64                 `protobuf:"varint,4,opt,name=new_parent,json=newParent,proto3" json:"new_parent,omitempty"` // New parent directory inode
	NewName       string                 `protobuf:"bytes,5,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`        // New name
	Flags         uint32                 `protobuf:"varint,6,opt,name=flags,proto3" json:"flags,omitempty"`                          // Rename flags
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameRequest) Reset() {
	*x = RenameRequest{}
	mi := &file_proto_filesystem_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameRequest) ProtoMessage() {}

func (x *RenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameRequest.ProtoReflect.Descriptor instead.
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{19}
}

func (x *RenameRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *RenameRequest) GetOldParent() uint64 {
	if x != nil {
		return x.OldParent
	}
	return 0
}

func (x *RenameRequest) GetOldName() string {
	if x != nil {
		return x.OldName
	}
	return ""
}

func (x *RenameRequest) GetNewParent() uint64 {
	if x != nil {
		return x.NewParent
	}
	return 0
}

func (x *RenameRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

func (x *RenameRequest) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

// Flush file
type FlushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`  // Volume identifier
	HandleId      uint64                 `protobuf:"varint,2,opt,name=handle_id,json=handleId,proto3" json:"handle_id,omitempty"` // File handle to flush
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushRequest) Reset() {
	*x = FlushRequest{}
	mi := &file_proto_filesystem_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushRequest) ProtoMessage() {}

func (x *FlushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushRequest.ProtoReflect.Descriptor instead.
func (*FlushRequest) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{20}
}

func (x *FlushRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *FlushRequest) GetHandleId() uint64 {
	if x != nil {
		return x.HandleId
	}
	return 0
}

// Synchronize file
type FsyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`  // Volume identifier
	HandleId      uint64                 `protobuf:"varint,2,opt,name=handle_id,json=handleId,proto3" json:"handle_id,omitempty"` // File handle to sync
	Datasync      bool                   `protobuf:"varint,3,opt,name=datasync,proto3" json:"datasync,omitempty"`                 // Sync only data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsyncRequest) Reset() {
	*x = FsyncRequest{}
	mi := &file_proto_filesystem_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsyncRequest) ProtoMessage() {}

func (x *FsyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsyncRequest.ProtoReflect.Descriptor instead.
func (*FsyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{21}
}

func (x *FsyncRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *FsyncRequest) GetHandleId() uint64 {
	if x != nil {
		return x.HandleId
	}
	return 0
}

func (x *FsyncRequest) GetDatasync() bool {
	if x != nil {
		return x.Datasync
	}
	return false
}

// Mount volume
type MountVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	Config        *VolumeConfig          `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountVolumeRequest) Reset() {
	*x = MountVolumeRequest{}
	mi := &file_proto_filesystem_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountVolumeRequest) ProtoMessage() {}

func (x *MountVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountVolumeRequest.ProtoReflect.Descriptor instead.
func (*MountVolumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{22}
}

func (x *MountVolumeRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *MountVolumeRequest) GetConfig() *VolumeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type VolumeConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MetaUrl        string                 `protobuf:"bytes,1,opt,name=meta_url,json=metaUrl,proto3" json:"meta_url,omitempty"`
	S3Bucket       string                 `protobuf:"bytes,2,opt,name=s3_bucket,json=s3Bucket,proto3" json:"s3_bucket,omitempty"`
	S3Prefix       string                 `protobuf:"bytes,3,opt,name=s3_prefix,json=s3Prefix,proto3" json:"s3_prefix,omitempty"`
	S3Region       string                 `protobuf:"bytes,4,opt,name=s3_region,json=s3Region,proto3" json:"s3_region,omitempty"`
	S3Endpoint     string                 `protobuf:"bytes,5,opt,name=s3_endpoint,json=s3Endpoint,proto3" json:"s3_endpoint,omitempty"`
	S3AccessKey    string                 `protobuf:"bytes,6,opt,name=s3_access_key,json=s3AccessKey,proto3" json:"s3_access_key,omitempty"`
	S3SecretKey    string                 `protobuf:"bytes,7,opt,name=s3_secret_key,json=s3SecretKey,proto3" json:"s3_secret_key,omitempty"`
	S3SessionToken string                 `protobuf:"bytes,8,opt,name=s3_session_token,json=s3SessionToken,proto3" json:"s3_session_token,omitempty"`
	CacheDir       string                 `protobuf:"bytes,9,opt,name=cache_dir,json=cacheDir,proto3" json:"cache_dir,omitempty"`
	CacheSize      string                 `protobuf:"bytes,10,opt,name=cache_size,json=cacheSize,proto3" json:"cache_size,omitempty"`
	Prefetch       int32                  `protobuf:"varint,11,opt,name=prefetch,proto3" json:"prefetch,omitempty"`
	BufferSize     string                 `protobuf:"bytes,12,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`
	Writeback      bool                   `protobuf:"varint,13,opt,name=writeback,proto3" json:"writeback,omitempty"`
	ReadOnly       bool                   `protobuf:"varint,14,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VolumeConfig) Reset() {
	*x = VolumeConfig{}
	mi := &file_proto_filesystem_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeConfig) ProtoMessage() {}

func (x *VolumeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeConfig.ProtoReflect.Descriptor instead.
func (*VolumeConfig) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{23}
}

func (x *VolumeConfig) GetMetaUrl() string {
	if x != nil {
		return x.MetaUrl
	}
	return ""
}

func (x *VolumeConfig) GetS3Bucket() string {
	if x != nil {
		return x.S3Bucket
	}
	return ""
}

func (x *VolumeConfig) GetS3Prefix() string {
	if x != nil {
		return x.S3Prefix
	}
	return ""
}

func (x *VolumeConfig) GetS3Region() string {
	if x != nil {
		return x.S3Region
	}
	return ""
}

func (x *VolumeConfig) GetS3Endpoint() string {
	if x != nil {
		return x.S3Endpoint
	}
	return ""
}

func (x *VolumeConfig) GetS3AccessKey() string {
	if x != nil {
		return x.S3AccessKey
	}
	return ""
}

func (x *VolumeConfig) GetS3SecretKey() string {
	if x != nil {
		return x.S3SecretKey
	}
	return ""
}

func (x *VolumeConfig) GetS3SessionToken() string {
	if x != nil {
		return x.S3SessionToken
	}
	return ""
}

func (x *VolumeConfig) GetCacheDir() string {
	if x != nil {
		return x.CacheDir
	}
	return ""
}

func (x *VolumeConfig) GetCacheSize() string {
	if x != nil {
		return x.CacheSize
	}
	return ""
}

func (x *VolumeConfig) GetPrefetch() int32 {
	if x != nil {
		return x.Prefetch
	}
	return 0
}

func (x *VolumeConfig) GetBufferSize() string {
	if x != nil {
		return x.BufferSize
	}
	return ""
}

func (x *VolumeConfig) GetWriteback() bool {
	if x != nil {
		return x.Writeback
	}
	return false
}

func (x *VolumeConfig) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type MountVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	MountedAt     int64                  `protobuf:"varint,2,opt,name=mounted_at,json=mountedAt,proto3" json:"mounted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountVolumeResponse) Reset() {
	*x = MountVolumeResponse{}
	mi := &file_proto_filesystem_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountVolumeResponse) ProtoMessage() {}

func (x *MountVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountVolumeResponse.ProtoReflect.Descriptor instead.
func (*MountVolumeResponse) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{24}
}

func (x *MountVolumeResponse) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *MountVolumeResponse) GetMountedAt() int64 {
	if x != nil {
		return x.MountedAt
	}
	return 0
}

type UnmountVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmountVolumeRequest) Reset() {
	*x = UnmountVolumeRequest{}
	mi := &file_proto_filesystem_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmountVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountVolumeRequest) ProtoMessage() {}

func (x *UnmountVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountVolumeRequest.ProtoReflect.Descriptor instead.
func (*UnmountVolumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{25}
}

func (x *UnmountVolumeRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_filesystem_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filesystem_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_filesystem_proto_rawDescGZIP(), []int{26}
}

var File_proto_filesystem_proto protoreflect.FileDescriptor

const file_proto_filesystem_proto_rawDesc = "" +
	"\n" +
	"\x16proto/filesystem.proto\x12\vsandbox0.fs\"\x89\x01\n" +
	"\vReadRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1b\n" +
	"\thandle_id\x18\x05 \x01(\x04R\bhandleId\"4\n" +
	"\fReadResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x02 \x01(\bR\x03eof\"\x8a\x01\n" +
	"\fWriteRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1b\n" +
	"\thandle_id\x18\x05 \x01(\x04R\bhandleId\"4\n" +
	"\rWriteResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten\"V\n" +
	"\vOpenRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\x12\x14\n" +
	"\x05flags\x18\x03 \x01(\rR\x05flags\"+\n" +
	"\fOpenResponse\x12\x1b\n" +
	"\thandle_id\x18\x01 \x01(\x04R\bhandleId\"J\n" +
	"\x0eReleaseRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x1b\n" +
	"\thandle_id\x18\x02 \x01(\x04R\bhandleId\"\x82\x01\n" +
	"\rCreateRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x16\n" +
	"\x06parent\x18\x02 \x01(\x04R\x06parent\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\x12\x14\n" +
	"\x05flags\x18\x05 \x01(\rR\x05flags\"k\n" +
	"\fMkdirRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x16\n" +
	"\x06parent\x18\x02 \x01(\x04R\x06parent\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\"\x93\x01\n" +
	"\fNodeResponse\x12\x14\n" +
	"\x05inode\x18\x01 \x01(\x04R\x05inode\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x120\n" +
	"\x04attr\x18\x03 \x01(\v2\x1c.sandbox0.fs.GetAttrResponseR\x04attr\x12\x1b\n" +
	"\thandle_id\x18\x04 \x01(\x04R\bhandleId\"C\n" +
	"\x0eGetAttrRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\"\xe5\x02\n" +
	"\x0fGetAttrResponse\x12\x10\n" +
	"\x03ino\x18\x01 \x01(\x04R\x03ino\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x14\n" +
	"\x05nlink\x18\x03 \x01(\rR\x05nlink\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x05 \x01(\rR\x03gid\x12\x12\n" +
	"\x04rdev\x18\x06 \x01(\x04R\x04rdev\x12\x12\n" +
	"\x04size\x18\a \x01(\x04R\x04size\x12\x16\n" +
	"\x06blocks\x18\b \x01(\x04R\x06blocks\x12\x1b\n" +
	"\tatime_sec\x18\t \x01(\x03R\batimeSec\x12\x1d\n" +
	"\n" +
	"atime_nsec\x18\n" +
	" \x01(\x03R\tatimeNsec\x12\x1b\n" +
	"\tmtime_sec\x18\v \x01(\x03R\bmtimeSec\x12\x1d\n" +
	"\n" +
	"mtime_nsec\x18\f \x01(\x03R\tmtimeNsec\x12\x1b\n" +
	"\tctime_sec\x18\r \x01(\x03R\bctimeSec\x12\x1d\n" +
	"\n" +
	"ctime_nsec\x18\x0e \x01(\x03R\tctimeNsec\"\x8b\x01\n" +
	"\x0eSetAttrRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\x12\x14\n" +
	"\x05valid\x18\x03 \x01(\rR\x05valid\x120\n" +
	"\x04attr\x18\x04 \x01(\v2\x1c.sandbox0.fs.GetAttrResponseR\x04attr\"C\n" +
	"\x0fSetAttrResponse\x120\n" +
	"\x04attr\x18\x01 \x01(\v2\x1c.sandbox0.fs.GetAttrResponseR\x04attr\"X\n" +
	"\rLookupRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x16\n" +
	"\x06parent\x18\x02 \x01(\x04R\x06parent\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"x\n" +
	"\x0eReadDirRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\x12\x1b\n" +
	"\thandle_id\x18\x03 \x01(\x04R\bhandleId\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\"T\n" +
	"\x0fReadDirResponse\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.sandbox0.fs.DirEntryR\aentries\x12\x10\n" +
	"\x03eof\x18\x02 \x01(\bR\x03eof\"\x92\x01\n" +
	"\bDirEntry\x12\x14\n" +
	"\x05inode\x18\x01 \x01(\x04R\x05inode\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\rR\x04type\x120\n" +
	"\x04attr\x18\x05 \x01(\v2\x1c.sandbox0.fs.GetAttrResponseR\x04attr\"X\n" +
	"\rUnlinkRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x16\n" +
	"\x06parent\x18\x02 \x01(\x04R\x06parent\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xb6\x01\n" +
	"\rRenameRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x1d\n" +
	"\n" +
	"old_parent\x18\x02 \x01(\x04R\toldParent\x12\x19\n" +
	"\bold_name\x18\x03 \x01(\tR\aoldName\x12\x1d\n" +
	"\n" +
	"new_parent\x18\x04 \x01(\x04R\tnewParent\x12\x19\n" +
	"\bnew_name\x18\x05 \x01(\tR\anewName\x12\x14\n" +
	"\x05flags\x18\x06 \x01(\rR\x05flags\"H\n" +
	"\fFlushRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x1b\n" +
	"\thandle_id\x18\x02 \x01(\x04R\bhandleId\"d\n" +
	"\fFsyncRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x1b\n" +
	"\thandle_id\x18\x02 \x01(\x04R\bhandleId\x12\x1a\n" +
	"\bdatasync\x18\x03 \x01(\bR\bdatasync\"d\n" +
	"\x12MountVolumeRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x121\n" +
	"\x06config\x18\x02 \x01(\v2\x19.sandbox0.fs.VolumeConfigR\x06config\"\xc7\x03\n" +
	"\fVolumeConfig\x12\x19\n" +
	"\bmeta_url\x18\x01 \x01(\tR\ametaUrl\x12\x1b\n" +
	"\ts3_bucket\x18\x02 \x01(\tR\bs3Bucket\x12\x1b\n" +
	"\ts3_prefix\x18\x03 \x01(\tR\bs3Prefix\x12\x1b\n" +
	"\ts3_region\x18\x04 \x01(\tR\bs3Region\x12\x1f\n" +
	"\vs3_endpoint\x18\x05 \x01(\tR\n" +
	"s3Endpoint\x12\"\n" +
	"\rs3_access_key\x18\x06 \x01(\tR\vs3AccessKey\x12\"\n" +
	"\rs3_secret_key\x18\a \x01(\tR\vs3SecretKey\x12(\n" +
	"\x10s3_session_token\x18\b \x01(\tR\x0es3SessionToken\x12\x1b\n" +
	"\tcache_dir\x18\t \x01(\tR\bcacheDir\x12\x1d\n" +
	"\n" +
	"cache_size\x18\n" +
	" \x01(\tR\tcacheSize\x12\x1a\n" +
	"\bprefetch\x18\v \x01(\x05R\bprefetch\x12\x1f\n" +
	"\vbuffer_size\x18\f \x01(\tR\n" +
	"bufferSize\x12\x1c\n" +
	"\twriteback\x18\r \x01(\bR\twriteback\x12\x1b\n" +
	"\tread_only\x18\x0e \x01(\bR\breadOnly\"Q\n" +
	"\x13MountVolumeResponse\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x1d\n" +
	"\n" +
	"mounted_at\x18\x02 \x01(\x03R\tmountedAt\"3\n" +
	"\x14UnmountVolumeRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\"\a\n" +
	"\x05Empty2\x93\b\n" +
	"\n" +
	"FileSystem\x12;\n" +
	"\x04Read\x12\x18.sandbox0.fs.ReadRequest\x1a\x19.sandbox0.fs.ReadResponse\x12>\n" +
	"\x05Write\x12\x19.sandbox0.fs.WriteRequest\x1a\x1a.sandbox0.fs.WriteResponse\x12?\n" +
	"\x06Create\x12\x1a.sandbox0.fs.CreateRequest\x1a\x19.sandbox0.fs.NodeResponse\x12=\n" +
	"\x05Mkdir\x12\x19.sandbox0.fs.MkdirRequest\x1a\x19.sandbox0.fs.NodeResponse\x128\n" +
	"\x06Unlink\x12\x1a.sandbox0.fs.UnlinkRequest\x1a\x12.sandbox0.fs.Empty\x12D\n" +
	"\aGetAttr\x12\x1b.sandbox0.fs.GetAttrRequest\x1a\x1c.sandbox0.fs.GetAttrResponse\x12D\n" +
	"\aSetAttr\x12\x1b.sandbox0.fs.SetAttrRequest\x1a\x1c.sandbox0.fs.SetAttrResponse\x12?\n" +
	"\x06Lookup\x12\x1a.sandbox0.fs.LookupRequest\x1a\x19.sandbox0.fs.NodeResponse\x12D\n" +
	"\aReadDir\x12\x1b.sandbox0.fs.ReadDirRequest\x1a\x1c.sandbox0.fs.ReadDirResponse\x128\n" +
	"\x06Rename\x12\x1a.sandbox0.fs.RenameRequest\x1a\x12.sandbox0.fs.Empty\x126\n" +
	"\x05Flush\x12\x19.sandbox0.fs.FlushRequest\x1a\x12.sandbox0.fs.Empty\x126\n" +
	"\x05Fsync\x12\x19.sandbox0.fs.FsyncRequest\x1a\x12.sandbox0.fs.Empty\x12;\n" +
	"\x04Open\x12\x18.sandbox0.fs.OpenRequest\x1a\x19.sandbox0.fs.OpenResponse\x12:\n" +
	"\aRelease\x12\x1b.sandbox0.fs.ReleaseRequest\x1a\x12.sandbox0.fs.Empty\x12P\n" +
	"\vMountVolume\x12\x1f.sandbox0.fs.MountVolumeRequest\x1a .sandbox0.fs.MountVolumeResponse\x12F\n" +
	"\rUnmountVolume\x12!.sandbox0.fs.UnmountVolumeRequest\x1a\x12.sandbox0.fs.EmptyB/Z-github.com/sandbox0-ai/storage-proxy/proto/fsb\x06proto3"

var (
	file_proto_filesystem_proto_rawDescOnce sync.Once
	file_proto_filesystem_proto_rawDescData []byte
)

func file_proto_filesystem_proto_rawDescGZIP() []byte {
	file_proto_filesystem_proto_rawDescOnce.Do(func() {
		file_proto_filesystem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_filesystem_proto_rawDesc), len(file_proto_filesystem_proto_rawDesc)))
	})
	return file_proto_filesystem_proto_rawDescData
}

var file_proto_filesystem_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_proto_filesystem_proto_goTypes = []any{
	(*ReadRequest)(nil),          // 0: sandbox0.fs.ReadRequest
	(*ReadResponse)(nil),         // 1: sandbox0.fs.ReadResponse
	(*WriteRequest)(nil),         // 2: sandbox0.fs.WriteRequest
	(*WriteResponse)(nil),        // 3: sandbox0.fs.WriteResponse
	(*OpenRequest)(nil),          // 4: sandbox0.fs.OpenRequest
	(*OpenResponse)(nil),         // 5: sandbox0.fs.OpenResponse
	(*ReleaseRequest)(nil),       // 6: sandbox0.fs.ReleaseRequest
	(*CreateRequest)(nil),        // 7: sandbox0.fs.CreateRequest
	(*MkdirRequest)(nil),         // 8: sandbox0.fs.MkdirRequest
	(*NodeResponse)(nil),         // 9: sandbox0.fs.NodeResponse
	(*GetAttrRequest)(nil),       // 10: sandbox0.fs.GetAttrRequest
	(*GetAttrResponse)(nil),      // 11: sandbox0.fs.GetAttrResponse
	(*SetAttrRequest)(nil),       // 12: sandbox0.fs.SetAttrRequest
	(*SetAttrResponse)(nil),      // 13: sandbox0.fs.SetAttrResponse
	(*LookupRequest)(nil),        // 14: sandbox0.fs.LookupRequest
	(*ReadDirRequest)(nil),       // 15: sandbox0.fs.ReadDirRequest
	(*ReadDirResponse)(nil),      // 16: sandbox0.fs.ReadDirResponse
	(*DirEntry)(nil),             // 17: sandbox0.fs.DirEntry
	(*UnlinkRequest)(nil),        // 18: sandbox0.fs.UnlinkRequest
	(*RenameRequest)(nil),        // 19: sandbox0.fs.RenameRequest
	(*FlushRequest)(nil),         // 20: sandbox0.fs.FlushRequest
	(*FsyncRequest)(nil),         // 21: sandbox0.fs.FsyncRequest
	(*MountVolumeRequest)(nil),   // 22: sandbox0.fs.MountVolumeRequest
	(*VolumeConfig)(nil),         // 23: sandbox0.fs.VolumeConfig
	(*MountVolumeResponse)(nil),  // 24: sandbox0.fs.MountVolumeResponse
	(*UnmountVolumeRequest)(nil), // 25: sandbox0.fs.UnmountVolumeRequest
	(*Empty)(nil),                // 26: sandbox0.fs.Empty
}
var file_proto_filesystem_proto_depIdxs = []int32{
	11, // 0: sandbox0.fs.NodeResponse.attr:type_name -> sandbox0.fs.GetAttrResponse
	11, // 1: sandbox0.fs.SetAttrRequest.attr:type_name -> sandbox0.fs.GetAttrResponse
	11, // 2: sandbox0.fs.SetAttrResponse.attr:type_name -> sandbox0.fs.GetAttrResponse
	17, // 3: sandbox0.fs.ReadDirResponse.entries:type_name -> sandbox0.fs.DirEntry
	11, // 4: sandbox0.fs.DirEntry.attr:type_name -> sandbox0.fs.GetAttrResponse
	23, // 5: sandbox0.fs.MountVolumeRequest.config:type_name -> sandbox0.fs.VolumeConfig
	0,  // 6: sandbox0.fs.FileSystem.Read:input_type -> sandbox0.fs.ReadRequest
	2,  // 7: sandbox0.fs.FileSystem.Write:input_type -> sandbox0.fs.WriteRequest
	7,  // 8: sandbox0.fs.FileSystem.Create:input_type -> sandbox0.fs.CreateRequest
	8,  // 9: sandbox0.fs.FileSystem.Mkdir:input_type -> sandbox0.fs.MkdirRequest
	18, // 10: sandbox0.fs.FileSystem.Unlink:input_type -> sandbox0.fs.UnlinkRequest
	10, // 11: sandbox0.fs.FileSystem.GetAttr:input_type -> sandbox0.fs.GetAttrRequest
	12, // 12: sandbox0.fs.FileSystem.SetAttr:input_type -> sandbox0.fs.SetAttrRequest
	14, // 13: sandbox0.fs.FileSystem.Lookup:input_type -> sandbox0.fs.LookupRequest
	15, // 14: sandbox0.fs.FileSystem.ReadDir:input_type -> sandbox0.fs.ReadDirRequest
	19, // 15: sandbox0.fs.FileSystem.Rename:input_type -> sandbox0.fs.RenameRequest
	20, // 16: sandbox0.fs.FileSystem.Flush:input_type -> sandbox0.fs.FlushRequest
	21, // 17: sandbox0.fs.FileSystem.Fsync:input_type -> sandbox0.fs.FsyncRequest
	4,  // 18: sandbox0.fs.FileSystem.Open:input_type -> sandbox0.fs.OpenRequest
	6,  // 19: sandbox0.fs.FileSystem.Release:input_type -> sandbox0.fs.ReleaseRequest
	22, // 20: sandbox0.fs.FileSystem.MountVolume:input_type -> sandbox0.fs.MountVolumeRequest
	25, // 21: sandbox0.fs.FileSystem.UnmountVolume:input_type -> sandbox0.fs.UnmountVolumeRequest
	1,  // 22: sandbox0.fs.FileSystem.Read:output_type -> sandbox0.fs.ReadResponse
	3,  // 23: sandbox0.fs.FileSystem.Write:output_type -> sandbox0.fs.WriteResponse
	9,  // 24: sandbox0.fs.FileSystem.Create:output_type -> sandbox0.fs.NodeResponse
	9,  // 25: sandbox0.fs.FileSystem.Mkdir:output_type -> sandbox0.fs.NodeResponse
	26, // 26: sandbox0.fs.FileSystem.Unlink:output_type -> sandbox0.fs.Empty
	11, // 27: sandbox0.fs.FileSystem.GetAttr:output_type -> sandbox0.fs.GetAttrResponse
	13, // 28: sandbox0.fs.FileSystem.SetAttr:output_type -> sandbox0.fs.SetAttrResponse
	9,  // 29: sandbox0.fs.FileSystem.Lookup:output_type -> sandbox0.fs.NodeResponse
	16, // 30: sandbox0.fs.FileSystem.ReadDir:output_type -> sandbox0.fs.ReadDirResponse
	26, // 31: sandbox0.fs.FileSystem.Rename:output_type -> sandbox0.fs.Empty
	26, // 32: sandbox0.fs.FileSystem.Flush:output_type -> sandbox0.fs.Empty
	26, // 33: sandbox0.fs.FileSystem.Fsync:output_type -> sandbox0.fs.Empty
	5,  // 34: sandbox0.fs.FileSystem.Open:output_type -> sandbox0.fs.OpenResponse
	26, // 35: sandbox0.fs.FileSystem.Release:output_type -> sandbox0.fs.Empty
	24, // 36: sandbox0.fs.FileSystem.MountVolume:output_type -> sandbox0.fs.MountVolumeResponse
	26, // 37: sandbox0.fs.FileSystem.UnmountVolume:output_type -> sandbox0.fs.Empty
	22, // [22:38] is the sub-list for method output_type
	6,  // [6:22] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_filesystem_proto_init() }
func file_proto_filesystem_proto_init() {
	if File_proto_filesystem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_filesystem_proto_rawDesc), len(file_proto_filesystem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_filesystem_proto_goTypes,
		DependencyIndexes: file_proto_filesystem_proto_depIdxs,
		MessageInfos:      file_proto_filesystem_proto_msgTypes,
	}.Build()
	File_proto_filesystem_proto = out.File
	file_proto_filesystem_proto_goTypes = nil
	file_proto_filesystem_proto_depIdxs = nil
}
