apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sandbox0-serving-cert
  namespace: sandbox0-system
spec:
  dnsNames:
  - manager.sandbox0-system.svc
  - manager.sandbox0-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: sandbox0-system
spec:
  selfSigned: {}
