apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: sandbox0-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: sandbox0-system/sandbox0-serving-cert
webhooks:
  - name: vsandboxtemplate.sandbox0.ai
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: manager
        namespace: sandbox0-system
        path: /validate-sandboxtemplate
        port: 443
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - sandbox0.ai
        apiVersions:
          - v1alpha1
        resources:
          - sandboxtemplates
    failurePolicy: Fail
    sideEffects: None
